Sprint 12
AnnaTau/ImageFeed pull request #5
Opened 2024-09-14 22:27 UTC by AnnaTau

2024-09-15 13:41 UTC, Kirchberg commented on ImageFeed/Constants.swift
> +    }
Ты молодец, что так разделяешь константы в разные контексты, это очень хороший и чистый подход ✨

2024-09-15 13:45 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListCell.swift
> +            debugPrint("[ImagesListCell configCell] Problem with URL \(photo.thumbImageURL)")
`debugPrint` это лучше, чем `print` 🔥

Для еще более лучшего подхода советую использовать `OSLog`, он уже используется для приложений, которые релизятся в AppStore. Благодаря `OSLog` мы можем выгрузить все логи с телефона и по нашему уникальному идентификатору приложения, найти логи нашего приложения и более точно оценить какие-то проблемы.

Вот несколько статей на эту тему:
– [OSLog and Unified logging as recommended by Apple](https://www.avanderlee.com/debugging/oslog-unified-logging/)
– [Modern logging with the OSLog framework in Swift](https://www.donnywals.com/modern-logging-with-the-oslog-framework-in-swift/)

2024-09-15 13:46 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListCell.swift
> +//            tableView.reloadRows(at: [indexPath], with: .automatic)
Было бы хорошо удалять не используемые строки кода

2024-09-15 13:50 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        fetchNextPhotos()
Рекомендую данный метод разгрузить таким образом:
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    setupLayout()
    setupNotifications()
    fetchNextPhotos()
}

...

private func setupLayout() {
    tableView.rowHeight = 200
    tableView.contentInset = UIEdgeInsets(top: 12, left: 0, bottom: 12, right: 0)
}

...

private func setupNotifications() {
    imagesListServiceObserver = ...
}
```

2024-09-15 13:52 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            .addObserver(
В данном случае было бы хорошо `.addObserver` оставить на одной строке с `NotificationCenter.default`, то есть:
```swift
NotificationCenter.default.addObserver(
    ...
)
```

2024-09-15 13:54 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListViewController.swift
>      private let showSingleImageSegueIdentifier = "ShowSingleImage"
Было бы хорошо данную строку выделить в константу внутри контроллера:
```swift

// MARK: - Private Types

private enum Constants {
    static let showSingleImageSegueIdentifier = "ShowSingleImage"
}

// MARK: - Private Properties

...
```

А использовать таким образом: `Constants.showSingleImageSegueIdentifier`

2024-09-15 13:55 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            case .success(let body):
Было бы хорошо убрать Warning: Immutable value 'body' was never used; consider replacing with '_' or removing it

2024-09-15 13:59 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                UIBlockingProgressHUD.dismiss()
⚠️ Успешный результат будет вызван на главном потоке, а ошибка нет. 

При показе ошибки мы также должны вернуться в главный поток, необходимо тут также обернуть в `DispatchQueue.main.async`

2024-09-15 14:04 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        imagesListService.fetchPhotosNextPage() { result in
Стоит сделать так, чтобы мы при использовании данных методов возвращали фотографии и обрабатывали их в этом месте. У нас есть переменная внутри контроллера, которая так и просится для заполнения после успешного полученного ответа `photos`.

2024-09-15 14:05 UTC, Kirchberg commented on ImageFeed/Models/Photo.swift
> +// MARK: - Data Model
После `MARK` стоит оставлять один пустой отступ, так проще найти данный `MARK`, особенно если файл будет слишком большой

2024-09-15 14:17 UTC, Kirchberg commented on ImageFeed/Profile/ProfileViewController.swift
> +        self.present(alert, animated: true, completion: nil)
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-09-15 14:19 UTC, Kirchberg commented on ImageFeed/Services/ImagesListService.swift
> +        if task != nil {
Стоит использовать для такой проверки вместо конструкции `if` конструкцию `guard`:
```swift
guard task == nil else {
    return
}
```

2024-09-15 14:23 UTC, Kirchberg requested changes
Привет, очень сильная работа ✨

Есть одно критическое и маленькое замечание, без его исправления, я, к сожалению, не смогу принять работу, но его можно будет быстро поправить.

В остальном все хорошо, мои комментарии носят рекомендательный характер 🤍

Буду ждать исправления, ты большой молодец 🔥

2024-09-15 20:43 UTC, AnnaTau commented on ImageFeed/ImagesList/ImagesListCell.swift
> +            debugPrint("[ImagesListCell configCell] Problem with URL \(photo.thumbImageURL)")
Очень крутая тема, но как я поняла она доступна с версии iOS 14 и выше, а в ТЗ требование iOS 13. Можно канеш пометить @available, но тогда получается для 13 версии логов вообще не будет?)

2024-09-16 06:54 UTC, Kirchberg commented on ImageFeed/ImagesList/ImagesListCell.swift
> +            debugPrint("[ImagesListCell configCell] Problem with URL \(photo.thumbImageURL)")
Тогда в текущем случае не нужно менять :) Просто учти в будущих проектах, что такое есть ✨

2024-09-16 06:57 UTC, Kirchberg approved these changes
Работа принята, ты большой молодец! 🔥

Успехов в следующих заданиях :)

2024-09-17 13:43 UTC, merged